-- Xóa user cũ để làm sạch môi trường
BEGIN
    EXECUTE IMMEDIATE 'DROP USER NgNam CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Bỏ qua nếu user không tồn tại
END;
/

-- Tạo user mới
CREATE USER NgNam IDENTIFIED BY 123;

GRANT CREATE SESSION TO NgNam;
GRANT CREATE TABLE TO NgNam;
GRANT CREATE SEQUENCE TO NgNam;
GRANT CREATE TRIGGER TO NgNam;
GRANT CREATE VIEW TO NgNam;
GRANT CREATE PROCEDURE TO NgNam;
GRANT UNLIMITED TABLESPACE TO NgNam;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO NgNam; -- Cần cho mã hóa AES
GRANT EXECUTE ON SYS.DBMS_RLS TO NgNam;    -- Cần cho VPD (nếu dùng)
GRANT EXECUTE ON SYS.DBMS_FGA TO NgNam;    -- Cần cho FGA (nếu dùng)
